# Generated by Django 5.0.13 on 2026-07-10 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterMultipleLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_logo', models.ImageField(upload_to='footer_logo/')),
                ('footer_logo_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=100, null=True)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site_logo/')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='site_favicon/')),
                ('site_title', models.CharField(blank=True, max_length=100, null=True)),
                ('site_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('site_address', models.TextField(blank=True, null=True)),
                ('site_facebook', models.URLField(blank=True, null=True)),
                ('site_linkedin', models.URLField(blank=True, null=True)),
                ('site_youtube', models.URLField(blank=True, null=True)),
                ('site_whatsapp', models.URLField(blank=True, null=True)),
                ('site_map', models.TextField(blank=True, null=True)),
                ('site_status', models.BooleanField(default=True)),
                ('site_footer_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitesetting.footermultiplelogo')),
            ],
        ),
    ]
